BackEnd/urls.py
from django.contrib import admin
from django.urls import path
from forms import views
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'',include('forms.urls')),
    url(r'',include('users.urls')),
]



from forms import views
from BackEnd import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forms/urls.py
from django.contrib import admin
from django.urls import path
from rest_framework.routers import SimpleRouter
from django.conf.urls import url,include
from forms import views
from forms.views import FreelancersViewSet,CompanyViewSet,CofounderViewSet,ProductViewSet,EditProductViewSet,JobOpeningViewSet,FundingViewSet,InternViewSet,FranchiseeViewSet,FranchisorViewSet
# SET THE NAMESPACE!
app_name = 'forms'
router = SimpleRouter()
router.register("freelancersprofile",FreelancersViewSet)
router.register("createcompany",CompanyViewSet,'createcompany')
router.register("createcofounder",CofounderViewSet,'createcofounder')
router.register("addnewproduct",ProductViewSet,'addnewproduct')
router.register("jobopening",JobOpeningViewSet,'jobopening')
router.register("intern",InternViewSet,'intern')
router.register("franchisee",FranchiseeViewSet,'franchisee')
router.register("franchisor",FranchisorViewSet,'franchisor')
router.register("fundingpost",FundingViewSet,'fundingpost')
router.register("edittheproduct/(?P<prod_pk>.*)",EditProductViewSet,'edittheproduct')

urlpatterns=[
    url(r'^cofndprofile/$',views.cofndprofile,name='cofndprofile'),
    url(r'^Company_profile/$',views.CompanyProfile,name='Company_profile'),
    url(r'^Add_Products/$',views.addProduct,name='addproduct'),
    url(r'^CreateJob/$',views.CreateJob,name='createjob'),
    url(r'^productedit/(?P<pk>.*)/$',views.editproddetails,name='editproductdetails'),
    url(r'^JobApplication/(?P<pk>.*)/$',views.applyforjob,name='joobapplication'),
    url(r'^ApplicantsList/(?P<pk>.*)/$',views.applicants,name='applicantslist'),
    url(r'^FullApplication/(?P<pk>.*)/$',views.fullapplication,name='fullapplication'),
    url(r'^freelancersform/',views.freelancersform,name='freelancersform'),
    url(r'^companies/',views.company_list,name='company_list'),
    url(r'^jobs/',views.Jobs_list,name='Jobs_list'),
    url(r'^jobapplicants/',views.applicants_list,name='applicants_list'),
    url(r'^freelancers/',views.freelancers_list,name='freelancers'),
    url(r'^cofounders/',views.cofounder_list,name='cofounders'),
    url(r'^interns/',views.intern_list,name='interns'),
    url(r'^fundings/',views.funding_list,name='fundings'),
    url(r'^',include(router.urls))

    ]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path

from rest_framework.routers import SimpleRouter
from django.conf.urls import url,include
from users import views
from users.views import UsersViewSet,UserloginViewSet,UserlistViewSet
# SET THE NAMESPACE!
app_name = 'users'
userrouter = SimpleRouter()
userrouter.register("Usersignup",UsersViewSet,'signupuser')
userrouter.register("userlogin",UserloginViewSet,'userlogin')
userrouter.register("allusers",UserlistViewSet,'allusers')

urlpatterns=[
	url(r'^signup/$',views.register,name='register'),
    url(r'^login/$',views.Userlogin,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^userlist/$',views.userlist,name='userlist'),
    url(r'^followed/(?P<pk>.*)/$',views.follow,name='follow'),
    url(r'^following/$',views.following,name='following'),
    url(r'^unfollowed/(?P<pk>.*)/$',views.unfollow,name='unfollow'),
    url(r'^',include(userrouter.urls))
    ]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forms/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

indiv = [('student','student'), ('enterpreneur','enterpreneur'), ('Businessman','Businessman'),('Employee','Employee')]
searching = [('startup-idea','startup-idea'), ('startup-company','startup-company')]
joinas = [('cofounder','cofounder'),('team-member','team-member'),('partner','partner'),('others','others')]
profas = [('student','student'), ('enterpreneur','enterpreneur'), ('Businessman','Businessman'),('Investor','Investor'),('Freelancers','Freelancers'),('Student Enterpreneur','Student Enterpreneur')]





class CompanyBase(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='CompanyUserProfile')
	logo=models.ImageField(upload_to='logo_pics',blank=True)
	brand_name=models.CharField(max_length=100,blank=False)
	company_name=models.CharField(max_length=100,blank=False)
	company_email=models.EmailField(blank=False)
	website=models.URLField()
	company_address=models.CharField(max_length=200,blank=False)
	city = models.CharField(max_length=200, blank=True)
	industry = models.CharField(max_length=100, blank=False)
	businesstype = models.CharField(max_length=200, blank=True)
	about_company=models.CharField(max_length=500,blank=False)
	created_at = models.DateTimeField(auto_now_add= True)

	def __str__(self):
		return self.company_name






class Products(models.Model):
	productcompany = models.ForeignKey(CompanyBase,on_delete=models.CASCADE, unique=False,related_name='Product_cmp')
	product_pic = models.ImageField(upload_to='product_pics',blank=True)
	prod_name = models.CharField(max_length=200,blank=True)
	minimum_no = models.CharField(max_length=10,blank=False)
	price = models.CharField(max_length=5,blank=False)
	description = models.CharField(max_length=300,blank=True)

	def __str__(self):
		return self.prod_name




class EduDetails(models.Model):
	name = models.ForeignKey(User,on_delete=models.CASCADE,related_name='Edu_user')
	college_name = models.CharField(max_length=200,blank=True)
	course_name = models.CharField(max_length=200,blank=True)
	passing_year = models.DateTimeField()
	grade = models.IntegerField(default= 0)

	def __str__(self):
		return self.college_name



class SKILLS(models.Model):
	name = models.CharField(max_length=30)
	class Meta:
		ordering = ['name']
			
	def __str__(self):
		return self.name

class CofounderExperience(models.Model):
	ex_company_name=models.ForeignKey(CompanyBase,on_delete=models.CASCADE,related_name='Cofounder_experience_company')
	job_post=models.CharField(max_length=300,null=False,blank=False)
	starting_date=models.DateTimeField()
	ending_date=models.DateTimeField()
	def __str__(self):
		return self.job_post


class CofounderProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='Cofounder_user')
	im = models.CharField(max_length=100,blank=False,choices=profas) #edit
	looking_for = models.CharField(max_length=100,blank=False,choices=searching) #edit
	industry = models.CharField(max_length=200,blank=False)
	join_startup_as = models.CharField(max_length=100,blank=False,choices=joinas)
	workat = models.CharField(max_length=200,blank=True)
	education = models.ForeignKey(EduDetails,on_delete=models.CASCADE,related_name='Cofounder_edu',blank=True)
	skills = models.ManyToManyField(SKILLS,blank=False)
	experience = models.ManyToManyField(CofounderExperience,blank=True)
	aboutyourself = models.CharField(max_length=400, blank=True)
	created_at = models.DateTimeField(auto_now_add= True)

	def __str__(self):
		return self.user.username


def create_profile(sender, **kwargs):
	if kwargs['created']:
		cofnd_profile = CofounderProfile.objects.create(user=kwargs['instance'])









jobtype = [('part_time','part_time'),('full_time','full_time'),('Freelancing_work','Freelancing_work'),('Internship','Internship')]

class JobOpening(models.Model):
	job_companyname = models.ForeignKey(CompanyBase,on_delete=models.CASCADE, unique=False,related_name='Company_details')
	jobtilte = models.CharField(max_length=200,blank=True,unique=True)
	location = models.CharField(max_length=200,blank=True)
	jobtype = models.CharField(max_length=100,blank=True,choices=jobtype)
	experience = models.CharField(max_length=80,blank=True)
	qualification = models.CharField(max_length=100,blank=False)
	last_date = models.DateTimeField()
	reqskills = models.ManyToManyField(SKILLS,blank=False)
	job_description=models.TextField(max_length=1000,blank=False)
	valid = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add= True)

	def __str__(self):
		return self.jobtilte



selfchoices = [('Student','Student'),('Employee','Employee')]
class JobApplication(models.Model):
	jobtilte = models.ForeignKey(JobOpening,on_delete=models.CASCADE,related_name='Job_adding')
	applicant = models.ForeignKey(User,on_delete=models.CASCADE,related_name='applicant_details')
	applyas = models.CharField(max_length=100,blank=False,choices=selfchoices)
	college_name = models.CharField(max_length=200,blank=False)
	course_name = models.CharField(max_length=200,blank=False)
	passing_year = models.DateTimeField(blank=False)
	grade = models.IntegerField(default= 0,blank=False)
	resume = models.FileField(upload_to='resume',blank=False)
	aboutapplicant =  models.TextField(max_length=400,blank=False)
	def __str__(self):
		return self.applicant.username


class WorkProfile(models.Model):
	jobapplication = models.ForeignKey(JobApplication,on_delete=models.CASCADE,related_name='workprofile')
	Company_name =  models.CharField(max_length=200,blank=True)
	Post =  models.CharField(max_length=100,blank=True)
	Start_date = models.DateTimeField(blank=True)
	end_date = models.DateTimeField(blank=True)
	def __int__(self):
		return self.pk







categories = [('Business Advisor','Business Advisor'),
				('Financial Advisor','Financial Advisor'),
				('Technical Advisor','Technical Advisor'),
				('Legal Advisor','Legal Advisor'),
				('Chater Accountant','Chater Accountant'),
				('Company secretary','Company secretary'),
				('Content Writter','Content Writter'),
				('Graphic Designer','Graphic Designer'),
				('Adv. Film Maker','Adv. Film Maker'),
				('Web Developer','Web Developer'),
				('Software Developer','Software Developer'),
				('App Developer','App Developer'),
				('Digital Marketing','Digital Marketing'),
				('Event Planner','Event Planner'),
				('Data Entry Operator','Data Entry Operator'),
				('Telecaller','Telecaller'),
				('Markeitng','Markeitng'),
				('Hr','Hr')]






class FreelancersProfile(models.Model):
	theuser = models.OneToOneField(User,on_delete=models.CASCADE,related_name='FreelancerUserProfile')
	im = models.CharField(max_length=100,blank=False,choices=indiv)
	qualification =  models.CharField(max_length=100,blank=False)
	workingas =  models.CharField(max_length=100,blank=False,choices=categories)
	interestedin =  models.CharField(max_length=200,blank=False)
	lookingfor = models.CharField(max_length=200,blank=False)
	skills = models.ManyToManyField(SKILLS,blank=False)
	workpay = models.IntegerField(default= 0,blank=False)
	prevwork = models.CharField(max_length=200,blank=False)
	industry = models.CharField(max_length=100,blank=False)
	portfoliolink = models.URLField(max_length=200,blank=False)
	about = models.TextField(max_length=400,blank=False)
	def __str__(self):
		return self.theuser.username


internim = [('Intern','Intern'),('Employee','Employee'),('Job Seeker','Job Seeker')]
class InternProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='Intern_user')
	im = models.CharField(max_length=100, blank=False, choices=internim)
	work_at=models.CharField(max_length=100,blank=True)
	education = models.CharField(max_length=100,blank=False)
	skills = models.ManyToManyField(SKILLS, blank=False)
	experience = models.ManyToManyField(CofounderExperience,blank=True)
	about=models.CharField(max_length=300,blank=True)

	def __str__(self):
		return self.user.username


investorim = [('Individual Investor','Individual Investor'),('Angel Investor','Angel Investor'),('Venture Capitalist','Venture Capitalist'),('Investor Group','Investor Group')]

class InvestorProfile(models.Model):
	user= models.OneToOneField(User,on_delete=models.CASCADE,related_name='Investor_user')
	im=models.CharField(max_length=100, blank=False, choices=investorim)
	area_of_invest=models.CharField(max_length=100,blank=False)
	firm_name=models.CharField(max_length=100,blank=False)
	website=models.URLField()
	investment_location=models.CharField(max_length=100,blank=False)
	investment_range=models.CharField(max_length=20,blank=True)
	previous_investment=models.CharField(max_length=20,blank=True)
	about=models.CharField(max_length=200,blank=True)

	def __str__(self):
		return self.user.username







class LookingForFranchise(models.Model):
	investment = models.CharField(max_length=100, blank=True)
	space = models.CharField(max_length=100, blank=True)
	location = models.CharField(max_length=100, blank=True)
	industry = models.CharField(max_length=100, blank=False)
	product_or_services=models.CharField(max_length=100,blank=True)
	description = models.TextField(blank=False)
	industry_type = models.CharField(max_length=100, blank=False)
	business_nature = models.CharField(max_length=100, blank=False)
	about_comapny = models.TextField(blank=False)
	created_at = models.DateTimeField(auto_now_add= True)

	def __str__(self):
		return self.industry


class Franchisor(models.Model):
	company_name = models.ForeignKey(CompanyBase,on_delete=models.CASCADE, unique=False,related_name='franchisor_company')
	providing=models.CharField(max_length=100,blank=False)
	brand_fee=models.CharField(max_length=10,blank=True)
	investment_req=models.CharField(max_length=100,blank=True)
	space_req=models.CharField(max_length=100,blank=True)
	staff_no=models.CharField(max_length=10,blank=True)
	monthly_sale=models.CharField(max_length=50,blank=False)

forms/admin.py
from django.contrib import admin
from django.contrib.admin import site, ModelAdmin

from forms.models import Franchisee,Franchisor,FundingPost,LookingForFranchise,InvestorProfile,InternProfile,FreelancersProfile,CofounderProfile,EduDetails,CompanyBase,Products,JobOpening,JobApplication,WorkProfile,SKILLS,CofounderExperience
#
# Register your models here.





admin.site.register(CofounderProfile)
admin.site.register(SKILLS)
admin.site.register(EduDetails)



admin.site.register(CompanyBase)


admin.site.register(Products)

admin.site.register(JobOpening)



admin.site.register(JobApplication)
admin.site.register(WorkProfile)




admin.site.register(FreelancersProfile)


admin.site.register(CofounderExperience)



admin.site.register(InternProfile)


admin.site.register(InvestorProfile)


admin.site.register(LookingForFranchise)

admin.site.register(Franchisor)

admin.site.register(Franchisee)

admin.site.register(FundingPost)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/tests.py
from django.test import TestCase

# Create your tests here.

templates/forms/Franchisee.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="container">
		{% if companyexist %}
			<form method="POST">
				{% csrf_token %}
				{{ franchiseeform.as_p }}
				<input type="submit" name="">
				}
			</form>
		{% else %}
			<h2>No company</h2>
		{% endif %}
	</div>
</body>
</html>

templates/forms/cofndprofile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>co-founder profile</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>



    <style> 
        h1 { 
            color: green; 
        } 
  
        .multipleSelection { 
            width: 300px; 
            background-color: #BCC2C1; 
        } 
  
        .selectBox { 
            position: relative; 
        } 
  
        .selectBox select { 
            width: 100%; 
            font-weight: bold; 
        } 
  
        .overSelect { 
            position: absolute; 
            left: 0; 
            right: 0; 
            top: 0; 
            bottom: 0; 
        } 
  
        #checkBoxes { 
            display: none; 
            border: 1px #8DF5E4 solid; 
        } 
  
        #checkBoxes label { 
            display: block; 
        } 
  
        #checkBoxes label:hover { 
            background-color: #4F615E; 
        }

        .edu{
            padding: 1rem;
        } 
    </style> 
</head>
<body>

        <form enctype="multipart/form-data" method="POST" action="">
              {% csrf_token %}

            <p>
                <label for="id_im">Im:</label> 
                <select name="im" required="" id="id_im">
                    <option value="" selected="">---------</option>

                    <option value="student">student</option>

                    <option value="enterpreneur">enterpreneur</option>

                    <option value="Businessman">Businessman</option>

                    <option value="Investor">Investor</option>

                    <option value="Freelancers">Freelancers</option>

                    <option value="Student Enterpreneur">Student Enterpreneur</option>

                </select>
            </p>
            <p>
                <label for="id_looking_for">Looking for:</label> 
                <select name="looking_for" required="" id="id_looking_for">
                    <option value="" selected="">---------</option>

                    <option value="startup-idea">startup-idea</option>

                    <option value="startup-company">startup-company</option>

                </select>
            </p>
            <p><label for="id_industry">Industry:</label> <input type="text" name="industry" maxlength="200" required="" id="id_industry"></p>
            <p><label for="id_join_startup_as">Join startup as:</label> <select name="join_startup_as" required="" id="id_join_startup_as">
              <option value="" selected="">---------</option>

              <option value="cofounder">cofounder</option>

              <option value="team-member">team-member</option>

              <option value="partner">partner</option>

              <option value="others">others</option>

            </select></p>
            <p><label for="id_workat">Workat:</label> <input type="text" name="workat" maxlength="200" id="id_workat"></p>
            <p><label for="id_education">Education:</label> </p>
                <p><label for="id_college_name">College name:</label> <input type="text" name="college_name" maxlength="200" id="id_college_name"></p>
                <p><label for="id_course_name">Course name:</label> <input type="text" name="course_name" maxlength="200" id="id_course_name"></p>
                <p><label for="id_passing_year">Passing year:</label> <input type="text" name="passing_year" required="" id="id_passing_year"></p>
                <p><label for="id_grade">Grade:</label> <input type="number" name="grade" value="0" required="" id="id_grade"></p>
            <p class="select-skill">
                <label for="id_skills">Skills:</label> 
                            
                <select name="skills" id="id_skills" multiple="" style="overflow: visible; display: none;" >
                    {% for theskill in Skills.all%}
                        <option value="{{ theskill.id }}">{{ theskill.name }}</option>
                    {% endfor %}

                </select>
            </p>



                <div class="multipleSelection"> 
                    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." style="width: 100%;">
                    <div class="selectBox" 
                        onclick="showCheckboxes()"> 
                        <select name="" id=""> 
                            <option>Select options</option> 
                        </select> 
                        <div class="overSelect"></div> 
                    </div> 
          
                    <div id="checkBoxes"> 
                            {% for theskill in Skills.all%}
                                <label for="{{ theskill.id }}"> 
                                    <input type="checkbox" id="{{ theskill.name }}" class="{{ theskill.id }}" /> 
                                    {{ theskill.name }}
                                </label> 
                            {% endfor %}
                        
                    </div> 
                </div> 
            <p><label for="id_aboutyourself">Aboutyourself:</label> <input type="text" name="aboutyourself" maxlength="400" id="id_aboutyourself"></p>
                          
            <h3>Experience:</h3>

            <div class="experience">
                {{ expform.management_form }}
                {% for form in expform.forms %}
                {{ form.errors }}
                    <div class="no-error">
                        <p>
                            <label for="id_form-0-ex_company_name">Ex company name:</label> 
                            <select name="form-0-ex_company_name" id="id_form-0-ex_company_name">
                                    <option value="" selected="">---------</option>

                                    
                                    {% for company in companies.all %}
                                        <option value="{{ company.id }}">{{ company.company_name }}</option>
                                    {% endfor %}

                            </select>
                        </p>
                        <p>
                            <label for="id_form-0-job_post">Job post:</label> 
                            <input type="text" name="form-0-job_post" maxlength="300" id="id_form-0-job_post">
                        </p>
                        <p>
                            <label for="id_form-0-starting_date">Starting date:</label> 
                            <input type="date" name="form-0-starting_date" id="id_form-0-starting_date">
                        </p>
                        <p>
                            <label for="id_form-0-ending_date">Ending date:</label> 
                            <input type="date" name="form-0-ending_date" id="id_form-0-ending_date">
                        </p>
                    </div>
                    {% endfor %}
                    <div class="addmore" id="clicktoadd" onclick="addnew()" style="cursor: pointer; text-decoration: underline;">
                        Add new experience
                    </div>
            </div>           

              
              <input type="submit" name="" value="Register" class="regis-sub" style="">
        </form>


    <div id="empty_exp_form" style="display: none;">
        <table class="no_error">
            <tbody>
                <tr>
                    <th>
                        <label for="id_form-__prefix__-ex_company_name">Ex company name:</label>
                    </th>
                    <td>
                        <select name="form-__prefix__-ex_company_name" id="id_form-__prefix__-ex_company_name">
                            <option value="" selected="">---------</option>

                            <option value="1">AnAlyst2</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_form-__prefix__-job_post">Job post:</label>
                    </th>
                    <td>
                        <input type="text" name="form-__prefix__-job_post" maxlength="300" id="id_form-__prefix__-job_post">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_form-__prefix__-starting_date">Starting date:</label>
                    </th>
                    <td>
                        <input type="date" name="form-__prefix__-starting_date" id="id_form-__prefix__-starting_date">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_form-__prefix__-ending_date">Ending date:</label>
                    </th>
                    <td>
                        <input type="date" name="form-__prefix__-ending_date" id="id_form-__prefix__-ending_date">
                    </td>
                </tr>
            </tbody></table>
    </div>

    


    <script type="text/javascript">
        var edunum = 1;
        function myfunc() {
            var form_idx = $('#id_form-TOTAL_FORMS').val();
            $('.experience').append($('#empty_exp_form').html().replace(/__prefix__/g, form_idx));
            $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) +1);
        }
        document.getElementById("clicktoadd").addEventListener("click",myfunc);
    </script>
    <script> 
        var show = true; 
        
        function showCheckboxes() { 
            var checkboxes =  
                document.getElementById("checkBoxes"); 
  
            if (show) { 
                checkboxes.style.display = "block"; 
                show = false; 
            } else { 
                checkboxes.style.display = "none"; 
                show = true; 
            } 
        } 

    </script> 
    <script type="text/javascript">
        jQuery(document).ready(function ($){
            $("select-skill").css("display","none");


        })
    </script>
    <script type="text/javascript">
            $('input[type="checkbox"]').click(function(){
                if($(this).prop("checked") == true){
                    var theid = $(this).attr("class");
                    //alert(theid);
                    cls = "#id_skills option[value =" +'"'+ theid +'"'+"]";
                    //alert(cls);
                    //var opt = document.getElementsByClassName(cls);
                    $("#id_skills option[value =" + theid +"]").prop("selected",true);
                    //alert($(cls).text())
                    //$(cls).setAttribute("selected","selected");
                    $(cls).prop("selected",true);
                   //alert($(cls).attr('value'))

                    
                }

            })
    </script>


    <!--<script type="text/javascript">
        function searchfunc(){
            var input, filter, checkbox, label, ckeckboxinput,i=0;
            input = document.getElementById('theinput');
            filter = input.value.toUpperCase();
            checkbox = document.getElementById("checkBoxes");
            label = $("#checkBoxes label");
            checkboxdatas = $("#checkBoxes label input");
            for(i=0;i<label.length;i++){
                checkboxinput = checkboxdatas[i];
                textvalue = checkboxinput.textContent || checkboxinput.innerText;
                if(textvalue.toUpperCase().indexOf(filter)> -1){
                    li[i].style.display = "block";
                }
                else{
                    li[i].style.display = "none";
                }
            }

        }
    </script>-->
<script>
    function myFunction() {

        $("#checkBoxes").css("display","block");
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('myInput');
  filter = input.value.toUpperCase();
   if(!filter){
    $("#checkBoxes").css("display","none");
  }
  ul = document.getElementById("checkBoxes");
  li = ul.getElementsByTagName('label');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("input")[0];
    b = $("#checkBoxes label input[type='checkbox']").eq(i);
    //alert(b.attr("id"));
    //txtValue = a.textContent || a.innerText;
    txtValue = b.attr("id");
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "block";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>
</body>
</html>

templates/forms/company_profile.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


	<div class="form_container">
		
		<form method="POST" action="{% url 'forms:Company_profile' %}">
			{% csrf_token %}
			{{companybase_form.as_p}}
			{{companyinfo_form.as_p}}
			<input type="submit" name="" value="submit" style="" class="Company_profile_submit">
		</form>

	</div>
</body>
</html>

templates/forms/editproduct.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<form action=""  method="POST" >
					{% csrf_token %}
					<p><label for="id_prod_name">Prod name:</label> <input type="text" name="prod_name" maxlength="200" id="id_prod_name"></p>
					<p><label for="id_minimum_no">Minimum no:</label> <input type="text" name="minimum_no" maxlength="10" id="id_minimum_no"></p>
					<p><label for="id_product_pic">Product pic:</label> <input type="file" name="product_pic" accept="image/*" id="id_product_pic"></p>
					<p><label for="id_price">Price:</label> <input type="text" name="price" maxlength="5" id="id_price"></p>
					<p><label for="id_description">Description:</label> <input type="text" name="description" maxlength="300" id="id_description"></p>
					<input type="submit" name="">
	</form>
</body>
</html>

templates/forms/login.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<form method="post" action="{% url 'users:login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}

        <label for="username"><i class="fa fa-user"></i> Username:</label>
        <input type="text" name="username" placeholder="Username">
		<label for="password"><i class="fa fa-lock"></i> Password:</label>
        <input type="password" name="password" placeholder="Password">
		<input type="submit" name="" value="Login" style="" class="login">
	</form>


</body>
</html>